### ISSUE TITLE
Add derived quantities

### ISSUE THREAD

**Issue by kdund** [JelleAalbers/blueice#6]
In some analyses, the analysis may be performed in a space that partially depends on nuisance parameters- e.g. reconstructed energy. Source and model classes could be modified to account for this, for example by interpolating the derived quantities between anchor points.

**Comment by JelleAalbers** [comment]
Hi Knut, thanks for the suggestion! Do I understand correctly that you would like some dimension in the real data (what you pass to LogLikelihood.set_data) to interpolate as the nuisance parameters change?

Because in principle all parameters, even S1, S2, depend on the nuisance parameters (leff, qy, etc), but once that dependence is taken into account in the simulation, the interpolating/morphing handles this.

**Comment by kdund** [comment]
Hey- 
Does that mean that the code would get a different data set for each anchor point? 
I guess one would have to interpolate those quantities between anchor points then. 
My suggestion (possibly not practicable for a while) is to just use detector-level variables that do not depend on nuisance parameters- pmt counts etc. Probably not possible to completely excise any dependency, but I thought I'd put it up as an idea.

**Comment by JelleAalbers** [comment]
Just to be sure I understand what you're saying:

Currently all the variation due to the nuisance parameters is supposed to be on the PDF and rate for each source; the datapoints you feed in are assumed fixed. For example, suppose you want to do compare two S1 LCE(r, z) maps (say for different PTFE reflectivity assumptions), then you currently need to take (S1, r, z) as your analysis space, rather than (cS1, r, z), since the S1->cS1 conversion depends on the LCE map.

You'd propose to change something so you can use cS1 as analysis space in this analysis, and the datapoints move rather than the PDF (if you move both nothing would change). Is that right? Or do you have something else in mind?

**Comment by kdund** [comment]
I think it depends on how careful one is in the treatment of nuisance parameters- 
if, say, cS1 is (really) cS1_0, i.e. the cS1 you get by assuming the nominal or reference nuisance parameters, and all pdfs are in that space, then this is an unnecessary complication. I do not think (in general) that the pdf and parameter shifts would cancel out.

**Comment by kdund** [comment]
This may be done most straightforwardly by introducing the new parameter in the source class as a derived quantity, which may then be used.
