### ISSUE TITLE
Binned likelihoods, pdfs

### ISSUE THREAD

**Issue by kdund** [JelleAalbers/blueice#7]
I am looking at adding functionality for binned likelihoods in blueice (the first wimp analysis will probably be binned, with bins derived from calibration data)
As the statistics available greatly over the analysis range, I believe bin size and shape should be as flexible as possible— my preference would be to use a function of the event data that returns a bin index.

My first idea was to simply re-purpose the XENONSource- add an analysis variable called "bin_index", compute that for each event, and use the index as an analysis variable. However, as both Source and Likelihood classes would need modification, my current approach is to create a BinnedSource, (Model) and Likelihood class inheriting from the un-binned counterparts and re-implementing what is needed. Does this sound sensible?

**Comment by JelleAalbers** [comment]
Hi Knut, I also think binned likelihoods would be a good addition. If we restrict ourselves to grid binning  it should not be difficult, since we already derive our density estimators from histograms which support this. This doesn't restrict ourselves to grids with evenly spaced bins, you can have e.g. bin edges  [0, 1, 2, 4] in one dimension and  [-2, 4, 5, 7] in another. The XENON100 likelihood function does not use a grid in (S1, S2), but there should exist some appropriate coordinate transformation to make it a grid.

If I'm not mistaken, Source and Model don't have to be changed at all, and LogLikelihood only has to change a bit:
 * `LogLikelihood.set_data` would need to make a different interpolator (using `self.morpher.make_interpolator`), which interpolates the PDF histograms of the sources themselves instead of the values of the interpolated histogram. 
 * `LogLikelihood.set_data` should compute the histogram of the data and store it as an attribute of self.
 * `LogLikelihood.__call__` should call the new interpolator (instead of `mus_interpolator` and `ps_interpolator`) to get the model histogram at the requested point in parameters space. Then it should compute the poisson (or maybe chi2 if the user insist) likelihood of the data histogram given the model histogram.

Would you be interested in looking into this? We can also do it together when I am in Stockholm if you'd like.

**Comment by kdund** [comment]
Hi, Jelle
I'll mail you with some (internal) background for why I think arbitrary bins could be helpful for us- working on a possible implementation now. Otherwise, I agree that the above method is sensible.
